# Generated by Django 3.1.4 on 2020-12-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0004_auto_20201225_1725'),
        ('quiz', '0002_useranswer_userexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleplay.cluster'),
        ),
    ]
