# Generated by Django 3.1.4 on 2020-12-27 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201226_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 9, 21, 46, 277449)),
        ),
    ]
