# Generated by Django 3.1.4 on 2020-12-27 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userexam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 9, 25, 50, 264783)),
        ),
    ]
