# Generated by Django 3.1.4 on 2020-12-27 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0004_auto_20201225_1725'),
        ('quiz', '0005_auto_20201227_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roleplay.cluster'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
