# Generated by Django 3.1.4 on 2020-12-27 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201227_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instructional_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.instructionalarea'),
        ),
    ]
