# Generated by Django 3.1.4 on 2020-12-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_casequestion_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casequestion',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
