# Generated by Django 3.1.4 on 2020-12-25 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleplay.case')),
            ],
        ),
    ]
