# Generated by Django 3.1.4 on 2020-12-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0003_auto_20201225_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_improvement',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_strength',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
