# Generated by Django 3.1.4 on 2020-12-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0003_casequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='case',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
    ]
